remote-module & install: Test if config source is found

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Author: Romain Ouabdelkader
 
+if [ ! -d src ]
+then
+    echo "Cannot find config source"
+    exit 1
+fi
+
 install_files=$(ls src/*/install 2> /dev/null)
 if [ "$install_files" == "" ]
 then
diff --git a/remote-module b/remote-module
--- a/remote-module
+++ b/remote-module
@@ -13,6 +13,12 @@ then
     exit 1
 fi
 
+if [ ! -d src ]
+then
+    echo "Cannot find config source"
+    exit 1
+fi
+
 function cleanup_remote() {
     git remote remove "$1"
     exit 3
